# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 135af839825359db9c33fd9fb84ab7663e832df5e684affb887978abe8533dc8734a73863f44f2ada4ad132917416bc8560a073ace538cb6c8503c4802218034

test:
  secret_key_base: 2a66f4f9534b591dcbd412b60cabaf04b206f76f951574979ee6ae2c806a3627b501d67b4caa816abd20c122bc13dcdbf4d790abd8d0393d814cbf6d24231769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
